### ISSUE TITLE
packing 24.1.0 was not uploaded 

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/packaging-feedstock#30]
### Comment:

While the pull request was merged it is not available on https://anaconda.org/conda-forge/packaging/files causing pull requests like https://github.com/conda-forge/langchainhub-feedstock/pull/6 to fail.

**Comment by nicoddemus** [comment]
Thanks for the ping, seems like that merge commit did not trigger the build for some reason.

I added a dummy commit to `main`, this now triggered a new build, let's hope this fixes it: https://github.com/conda-forge/packaging-feedstock/runs/26123566731

**Comment by jan-janssen** [comment]
Perfect - it's fixed now.
